instruments:
  1:
    wave: sine
    filters:
      - adsr:
  2:
    wave: square
    filters:
      - adsr:
  3:
    wave: triangle
    filters:
      - adsr:
  4:
    wave: saw
    filters:
      - adsr:
  5:
    wave: sine
    filters:
      - distortion:
          value: 1.5
      - adsr:
  6:
    wave: sine
    filters:
      - adsr:
      - delay:
          interval:
            knob: 2
            default: 1.0
            delta: 0.125
          fade: 0.5
          times: 2
  7:
    wave: sine
    filters:
      - am:
          wave: sine
          frequency: 5.0
          amplitude: 1.0
      - adsr:
  8:
    wave: sine
    filters:
      - vibrato:
          wave: sine
          frequency: 4.0
          amplitude: 0.005
  9:
    wave: sine
    filters:
    - timeshift:
        wave: sine
        frequency: 4.0
        amplitude: 0.05

samples:
  4k:
    sample: "samples/4-kick.wav"
  4s:
    sample: "samples/4-snare.wav"
  4h:
    sample: "samples/4-hat.wav"
    filters:
      - delay:
          interval: 0.125
          fade: 0.5
          times: 3
  2k:
    sample: "samples/2-1-kick.wav"
  2t:
    sample: "samples/2-2-tom.wav"
  2s:
    sample: "samples/2-3-snare.wav"
  2r:
    sample: "samples/2-5-rim.wav"
  2l:
    sample: "samples/2-6-clap.wav"
  2a:
    sample: "samples/2-7-tambourine.wav"
  2h:
    sample: "samples/2-9-hat.wav"
  2o:
    sample: "samples/2-10-high-tom.wav"
  2p:
    sample: "samples/2-11-hat-open.wav"
  2n:
    sample: "samples/2-13-snare-2.wav"
  2i:
    sample: "samples/2-14-ride.wav"
  2z:
    sample: "samples/2-16-crash.wav"

